# Generated by Django 6.0.3 on 2026-03-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_username_profile_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='User',
        ),
    ]
